---
title: "homework-02"
author: "Chun Pong Brian Chan"
date: "9/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nycflights13)
library(tidyverse)

```

```{r}
flights

```

## Question 1

```{r flights}
count(flights, is.na(dep_time))
count(flights, is.na(dep_delay))
count(flights, is.na(arr_time))
count(flights, is.na(arr_delay))
count(flights, is.na(tailnum))
count(flights, is.na(air_time))
##sum(is.na.data.frame(flights))
```
I am quite sure these are quite self-explanatory with the name of the variable.


## Question 2

```{r flights}
transmute(flights, 
          dep_time, 
          minute = ((dep_time %/% 100) * 60) + (dep_time %% 100))
```


## Question 3

```{r flights}
transmute(flights, 
          dep_time, 
          minute = ((dep_time %/% 100) * 60) + (dep_time %% 100))
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
